import {
  mockAnalyticsCaseTypes,
  mockAnalyticsPriorities,
  mockAnalyticsStatuses,
  mockAnalyticsSummary,
  mockCasePriorityData,
  mockCaseStatusData,
  mockEvidenceAnalytics,
  mockEvidenceTypeData,
  mockInvestigatorPerformance,
  mockLawyerActivity,
  mockMonthlyCaseActivity,
  mockMonthlyEvidenceUploads,
  mockRiskAnalytics,
  mockTimelineAnalytics,
  mockVerificationRate,
} from '../data/mockData';

export const analyticsService = {
  getSummary: () => mockAnalyticsSummary,
  getCaseStatusData: () => mockCaseStatusData,
  getCasePriorityData: () => mockCasePriorityData,
  getEvidenceTypeData: () => mockEvidenceTypeData,
  getMonthlyCaseActivity: () => mockMonthlyCaseActivity,
  getMonthlyEvidenceUploads: () => mockMonthlyEvidenceUploads,
  getVerificationRate: () => mockVerificationRate,
  getInvestigatorPerformance: () => mockInvestigatorPerformance,
  getLawyerActivity: () => mockLawyerActivity,
  getEvidenceAnalytics: () => mockEvidenceAnalytics,
  getTimelineAnalytics: () => mockTimelineAnalytics,
  getRiskAnalytics: () => mockRiskAnalytics,
  getCaseTypes: () => mockAnalyticsCaseTypes,
  getPriorities: () => mockAnalyticsPriorities,
  getStatuses: () => mockAnalyticsStatuses,
};
